
package PopGenetics;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class PopulationGenetics extends ViewableDigraph {

	public PopulationGenetics() {
		super("PopGenetics");

		ViewableAtomic Fitness = new Fitness("Fitness");
		ViewableAtomic Generator = new Generator("Generator", 0); // second argument is delta_theta
		ViewableAtomic Transducer = new Transducer("Transducer", 1000); // second argument is # of generations

		add(Fitness);
		add(Generator);
		add(Transducer);

		addOutport("out_population");

		addCoupling(Generator, "out_population", Fitness, "in_population");
		addCoupling(Generator, "delta_theta", Fitness, "delta_theta");
		addCoupling(Fitness, "out_population", Transducer, "in_population");
		
		addCoupling(Fitness, "out_population", this, "out_population");
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 145);
        ((ViewableComponent)withName("Fitness")).setPreferredLocation(new Point(240, 50));
        ((ViewableComponent)withName("Generator")).setPreferredLocation(new Point(27, 50));
    }
}
