
package PopGenetics;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class PopulationGenetics extends ViewableDigraph {

	public PopulationGenetics() {
		super("RMSD");

		ViewableAtomic Fitness = new Fitness("Fitness");
		ViewableAtomic Generator = new Generator("Generator", 0); // first argument is delta_theta

		add(Fitness);
		add(Generator);

		addOutport("out_population");
//		addOutport("outRed");

		addCoupling(Generator, "out_population", Fitness, "in_population");
		addCoupling(Generator, "delta_theta", Fitness, "delta_theta");
//		addCoupling(Requester, "outRed", MSD, "inRed");

//		addCoupling(MSD, "outGreen", this, "outGreen");
		addCoupling(Fitness, "out_population", this, "out_population");
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 145);
        ((ViewableComponent)withName("Fitness")).setPreferredLocation(new Point(240, 50));
        ((ViewableComponent)withName("Generator")).setPreferredLocation(new Point(27, 50));
    }
}
